export  const Data = [
    {
        id:1,
        img1: "/img/Readersimg.png",
        img2:'/img/Star.svg',
        img3:'/img/tick.png',
        img4:"/img/Calling.png",
        img5:"/img/Chat.png",
        text1:"7899",
        text2:"Orders",
        name:"Umakant padit",
        lang:"Hindi",
        exp:"Exp :",
        year:"12 Years",
        free:"FREE",
        min:"50/Min",
        call:"Call",
        chat:"Chat",
        desk:"Career",
    },
    {   id:2,
        img1: "/img/Readersimg.png",
        img2:'/img/Star.svg',
        img3:'/img/tick.png',
        img4:"/img/Calling.png",
        img5:"/img/Chat.png",
        text1:"7899",
        text2:"Orders",
        name:"Prit joshi",
        lang:"English",
        exp:"Exp :",
        year:"12 Years",
        free:"FREE",
        min:"50/Min",
        call:"Call",
        chat:"Chat",
        desk:"Business",
    },
    {   id:3,
        img1: "/img/Readersimg.png",
        img2:'/img/Star.svg',
        img3:'/img/tick.png',
        img4:"/img/Calling.png",
        img5:"/img/Chat.png",
        text1:"7899",
        text2:"Orders",
        name:"Ritesh Aditya",
        lang:"Gujarati",
        exp:"Exp :",
        year:"12 Years",
        free:"FREE",
        min:"50/Min",
        call:"Call",
        chat:"Chat",
        desk:"Job",
    },
    {   id:4,
        img1: "/img/Readersimg.png",
        img2:'/img/Star.svg',
        img3:'/img/tick.png',
        img4:"/img/Calling.png",
        img5:"/img/Chat.png",
        text1:"7899",
        text2:"Orders",
        name:"Acharya Aditya",
        lang:"Bengali",
        exp:"Exp :",
        year:"12 Years",
        free:"FREE",
        min:"50/Min",
        call:"Call",
        chat:"Chat",
        desk:"Love",
    },
    {   id:5,
        img1: "/img/Readersimg.png",
        img2:'/img/Star.svg',
        img3:'/img/tick.png',
        img4:"/img/Calling.png",
        img5:"/img/Chat.png",
        text1:"7899",
        text2:"Orders",
        name:"Acharya Aditya",
        lang:"Marathi",
        exp:"Exp :",
        year:"12 Years",
        free:"FREE",
        min:"50/Min",
        call:"Call",
        chat:"Chat",
        desk:"Marriage",
    },
    {  id:6,
        img1: "/img/Readersimg.png",
        img2:'/img/Star.svg',
        img3:'/img/tick.png',
        img4:"/img/Calling.png",
        img5:"/img/Chat.png",
        text1:"7899",
        text2:"Orders",
        name:"Acharya Aditya",
        lang:"Bengali",
        exp:"Exp :",
        year:"30 Years",
        free:"FREE",
        min:"50/Min",
        call:"Call",
        chat:"Chat",
        desk:"Relationship",
    }, 
    {  id:7,
      img1: "/img/Readersimg.png",
      img2:'/img/Star.svg',
      img3:'/img/tick.png',
      img4:"/img/Calling.png",
      img5:"/img/Chat.png",
      text1:"7899",
      text2:"Orders",
      name:"Acharya Aditya",
      lang:"English , Hindi , Gujarati",
      exp:"Exp :",
      year:"25 Years",
      free:"FREE",
      min:"50/Min",
      call:"Call",
      chat:"Chat",
      desk:"Education",
  }, 
  {  id:8,
      img1: "/img/Readersimg.png",
      img2:'/img/Star.svg',
      img3:'/img/tick.png',
      img4:"/img/Calling.png",
      img5:"/img/Chat.png",
      text1:"7899",
      text2:"Orders",
      name:"Acharya Aditya",
      lang:"Telugu",
      exp:"Exp :",
      year:"16 Years",
      free:"FREE",
      min:"50/Min",
      call:"Call",
      chat:"Chat",
      desk:"Finance",
  }, 
  {  id:9,
      img1: "/img/Readersimg.png",
      img2:'/img/Star.svg',
      img3:'/img/tick.png',
      img4:"/img/Calling.png",
      img5:"/img/Chat.png",
      text1:"7899",
      text2:"Orders",
      name:"Acharya Aditya",
      lang:"Tamil",
      exp:"Exp :",
      year:"18 Years",
      free:"FREE",
      min:"50/Min",
      call:"Call",
      chat:"Chat",
      desk:"Gemstone",
  }, 
  {  id:10,
      img1: "/img/Readersimg.png",
      img2:'/img/Star.svg',
      img3:'/img/tick.png',
      img4:"/img/Calling.png",
      img5:"/img/Chat.png",
      text1:"7899",
      text2:"Orders",
      name:"Acharya Aditya",
      lang:"Gujarati",
      exp:"Exp :",
      year:"20 Years",
      free:"FREE",
      min:"50/Min",
      call:"Call",
      chat:"Chat",
      desk:"Foreign Travel",
  }, 
  ]